version: '3.8'

services:
    mysql:
        image: mysql:5.7.24
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'chat'

    app:
        build: src/chatbot
        restart: always
        container_name: myapp-web
        ports:
            - "80:80"
        volumes:
            - ./src/chatbot:/var/www/myapp
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOSTS: 'mysql'
            PMA_USER: 'root'
            PMA_PASSWORD: 'example'
        depends_on:
            - mysql
